### ISSUE TITLE
Compress Stylus output

### ISSUE THREAD

**Issue by corysimmons** [gmanricks/jeet-npm#1]
Is it an easy fix to tag the -c tag on the end of the Stylus compiling?

I looked at jeet.js but didn't see a place to insert compression.

**Comment by ozamorowski** [comment]
line 181 :
`styleFile = stylus(styleFile.toString()).set('paths', [cssPath + "styl"]).use(nib()).render();`

I don't really now node, but stylus docs have option `.set('compress', true)` , so it probodly should be:

```
styleFile = stylus(styleFile.toString()).set('paths', [cssPath + "styl"]).set('compress', true).use(nib()).render();
```

**Comment by corysimmons** [comment]
Ah I see. I figured it'd be something easy like that.

Too busy to break it without Gabriel around to clean up my mess right now.

**Comment by ozamorowski** [comment]
It's working. Pull on the way, I just forgot to reference to the issue... :P
