### ISSUE TITLE
Compiler throwing charAt error

### ISSUE THREAD

**Issue by corysimmons** [gmanricks/jeet-npm#12]
Fresh project, `jeet watch`:

```
Error in custom.styl on line 10
    6|
    7| // Mobile
    8| bp()
    9|
 > 10| endbp()

Object false has no method 'charAt'
```

Line 31 - https://github.com/CorySimmons/jeet-npm/blob/d5803ff40af41743cc48fbf5f4b565d53c2e3f6e/lib/compiler.coffee

Temporary solution:

```
npm install -g jeet@3.0.4
jeet create foo --ignore
jeet watch
```

**Comment by corysimmons** [comment]
Yay!

**Comment by bradleygirl** [comment]
I wish this was working for me. 
result after following the above solution: 

<pre>
 if (d.toString() !== data.pushed_at) {
TypeError: Cannot call method 'toString' of undefined
at C:\...\Application Data\npm\node_modules\jeet\lib\create.js:159:17
at fs.js:207:20
at Object.oncomplete (fs.js:107:15)
</pre>
