### ISSUE TITLE
After npm install Mavericks

### ISSUE THREAD

**Issue by jmcbade** [gmanricks/jeet-npm#18]
Mavericks latest and greatest.  Node.js was installed from the package distribution. Node -v returns: v0.10.26

After install, jeet -h returns: -bash: jeet: command not found

Permission / path issue?

**Comment by corysimmons** [comment]
Hi @jmcbade I think you're using an old version of Jeet (the one with the watcher and typography and all that). We've changed Jeet into a grid system only, and only a Stylus or SCSS library, so it's more modular and can be used in tandem with a lot of other things.

Check out the instructions at https://github.com/mojotech/jeet#jeet-grid-system for your preferred syntax and everything should work as expected.

If you're determined to use this older version of Jeet, you can try to `npm install -g jeet@3.0.19` to install this older version, but you really don't want to do that.

If you need a watcher, check out Roots (the version 3 branch), HarpJS, Metalsmith, or simply write your own Grunt (or Gulp) file.

Let me know if you need anything else and please report all future issues to https://github.com/mojotech/jeet/issues

**Comment by jmcbade** [comment]
Actually, I was installing the newer one, but I was confused as to where to put the issue.  It turned out to be a need to repair permissions.  I have another friend who had the same problem on her MAC as well.

Thanks for your time to reply!

**Comment by corysimmons** [comment]
The newer one isn't really a command line client. It simply houses a global copy of the Stylus version of Jeet, typically in `/usr/local/lib/node_modules/jeet`. Then you `-u jeet` with Stylus like `stylus -u jeet -w myFile.styl`. Within `myFile.styl` you put `@import 'jeet'` to call it.

It's a bit confusing tbh. I'll try to work on making this cleaner without sacrificing the modularity of the code.

So everything is working now?

**Comment by jmcbade** [comment]
It's very late here.  I will test things tomorrow.  I have Stylus working and installed.  I will try Jeet now when I am more awake.  I will be sure and follow up.  

Again, thanks for following up.  I am really curious to play with this.

**Comment by corysimmons** [comment]
:+1:

**Comment by jmcbade** [comment]
Ok, as I start my day here and look to some possible "exploration" in the land of things "Jeet", I was looking at the instructions between using SCSS and Stylus, and they are in essence, the same right?   So, (maybe this should be obvious to me but... face :palm_tree: ), Am I correct in presuming that the same Jeet package will work with either, and you just use the one you like, then Jeet picks up the scent?

**Comment by corysimmons** [comment]
@jmcbade Each has it's own installation/usage instructions.
- https://github.com/mojotech/jeet/tree/master/scss
- https://github.com/mojotech/jeet/tree/master/stylus

**Comment by jmcbade** [comment]
Cory,

Thank you for the correction on the paths. Wiping the sleep from my eyes here...

My training and experience have "holes" in them for sure. I'm new to Node.js and npm. So I guess I made an presumption, (I try to never 'ass-u-me' :), that the Jeet package got stored somewhere I could just globally call it up / copy it to a project each time I wanted to use it. I guess I presumed npm stored the Jeet packages somewhere and didn't require me to be online after that. So, I looked at the path in /usr/local/lib/node_modules/jeet and yep, Jeet folder is there, along with a subfolder "stylus" with a Jeet package there. 

See, I may want to make parallel test projects using Jeet with Stylus, and then with SASS, which I do have some experience with.  Now, what happens if I npm the SASS version as well?  Does npm then pick the right one to go with the css preprocessor I specify?  And since they have both been npm 'ed once each, npm uses the local copy now to populate the new project?

Do I have it correct now?  I bet you will cover this in your next tutorial movie :)  Thanks for your patience on this as I get my head around the process.

**Comment by corysimmons** [comment]
npm has nothing to do with the sass version, hence the directions are `svn checkout https://github.com/mojotech/jeet/trunk/scss/jeet` for the scss version

**Comment by jmcbade** [comment]
Face palm again?  Um.. You did say that the npm was for an earlier Jeet.  I guess it's just not handled by npm anymore then?  And you just svn a package in the flavor you want.  So I should just make local copies of each and then copy them over to projects accordingly? Right.  I see your updated to my last comment just now. Time for some caffeine

**Comment by jmcbade** [comment]
Cory,

Are you aware that this link is returning a 404?

> https://github.com/mojotech/jeet/trunk/scss/jeet

Also, I have yet to get Jeet to work with any CSS preprocessor.  I know you want more than "it doesn't work", but even when I do what seems to be recommended, using npm and stylus, I get a response that the Jeet code is not found in the npm modules folder.  I'm on a MAC, running Mavericks.  If I install without sudo, I get access errors.  If I install with using sodu, it completes, but then, as I said, I get the Jeet not found in the npm modules folder.  I looked, in /usr/local/lib/node_modules/jeet and it is there.

I have been watching for updated tutorials from the links I am finding in various places.  Noting that has solved this for me.

Love to try this out, when I can get it to work.  Sorry for making this a support thread, but I don't know where else to contact you.

**Comment by corysimmons** [comment]
You should almost never `sudo`.
- `sudo npm uninstall -g jeet`
- `sudo chown -R $USER /usr/local`
- `npm install -g jeet`

If you just want to toy around with it for a few days, try out the Stylus package at http://bit.ly/jeetfork

**Comment by TerryKLin** [comment]
I have the same issue with exactly the same environment and setup as jmcbade. I have to run sudo command in order for me to install jeet. 

Although I successfully installed jeet on my Mac, it wouldn't work for me at all. (The terminal said it compiled my .styl file)

Do you have any suggestions for this kind of problem?

Thanks in advance.

**Comment by corysimmons** [comment]
You don't have to use sudo and you should use it insanely sparingly. http://howtonode.org/introduction-to-npm

Can you replicate the exact steps you took?

**Comment by TerryKLin** [comment]
Hi, Cory

Sure. I downloaded Sublime Text 2 first, and install both node.js and
package control.

And then I installed Emmet and Stylus without any problem

However, I just can't install jeet without getting into sudo.

The attachment is the error msg I received if I don't install it without
sudo.

I know I have done something wrong and I am new to both Mac and the whole
npm procedure.

If you have any idea where I did wrong, please let me know.

Thank you very much

Terry

**Comment by corysimmons** [comment]
- `npm uninstall -g jeet`
- `sudo chown -R $USER /usr/local`
- `npm install -g jeet`

**Comment by TerryKLin** [comment]
Hi Cory

Sorry to trouble you again.

I tried to run the first command in terminal, but the error msg said that I
had to run it as admin.

The attachment is the error msg I've encountered when I tried to run it.

Do you know any other way around this?

Terry

**Comment by corysimmons** [comment]
Are you on Windows? If you are, right click on Command Prompt and click "Run as Administrator", if you're on a *nix system (Linux or OSX) then it should prompt you to enter your password when you try to run a `sudo` command which will effectively put you in "Administrative mode".

**Comment by corysimmons** [comment]
Oh, lolol, `jeet-npm` hasn't been worked on in ages. This is the wrong repo bro. You're looking for http://github.com/mojotech/jeet

Ignore this repo completely.

**Comment by TerryKLin** [comment]
Hi Cory,

There seems to be a bit of misunderstanding, probably from my side.

I followed the npm instruction from here,
https://github.com/mojotech/jeet/tree/master/stylus

And I got the exact error as the one I first sent you, which was the
permission error. (Can't run that command without getting into sudo)

Even if I did run it with sudo, the terminal would say it compiled the
.styl file into .css, but the website layout stays the same.

I hope it clarifies my exact problem.

Thanks,

Terry

**Comment by corysimmons** [comment]
Did you try to do this?
- `npm uninstall -g jeet`
- `sudo chown -R $USER /usr/local`
- `npm install -g jeet`

**Comment by TerryKLin** [comment]
Yeah, but I got stuck in the first step.

Do you want me to remove it with the admin privilege? (It's how I installed
in the first place)

**Comment by corysimmons** [comment]
`sudo npm uninstall -g jeet`

**Comment by TerryKLin** [comment]
Thanks for your help, I've got it installed.

I will let you know if I have any other question.

Thanks again

**Comment by TerryKLin** [comment]
Hi, Cory

This is Terry.

I have encountered a problem for a couple days and I'm not sure where went
wrong.

I have followed the usage example from the following link, but both "aside"
and article aren't behave as they are specified.

https://github.com/mojotech/jeet/tree/master/stylus
​

The attachment is what I have on my screen right now along with the html
and .styl files.

Do you know where it could have gone wrong?

Thanks,

Terry

**Comment by corysimmons** [comment]
What attachment?

**Comment by TerryKLin** [comment]
The attachment in the last email.

I have attached them again.

Sorry about the confusion.
