### ISSUE TITLE
jeet watch only compiles the first time

### ISSUE THREAD

**Issue by charliemagee** [gmanricks/jeet-npm#3]
I'm running on a Mac with up-to-date Ruby, Compass, and Jeet. Live Reload extension is turned on correctly in Chrome. I create a new Jeet project, open the index.html page in Chrome, cd to the directory, run jeet watch. It immediately compiles the scss file and reloads it.

But it fails to compile/reload on any additional saves to scss file, unless I rerun jeet watch.

Compass watch runs correctly, but doesn't reload.

**Comment by corysimmons** [comment]
Jeet's been updated and not that we really supported the old npm package (sorry about that! sometimes I miss these things), but I'm sure the new one fixes this issue.
